name: Run Edge Function Daily

on:
  schedule:
    - cron: "0 0 * * *" # This runs the job every day at midnight UTC

jobs:
  run-edge-function:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Edge Function
        run: |
          curl -L -X POST 'https://jwtjcjhnydruksviforg.supabase.co/functions/v1/tmdb-sync' -H 'Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}' --data '{"name":"Functions"}'
